os: linux
dist: focal
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    update: true
    packages:
      - cmake
      - libboost-all-dev
      - libtbb-dev
before_install:
  - sudo apt remove --purge python
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env update --file ${TRAVIS_BUILD_DIR}/test/pytest/environment.yml --name base
script:
  - mkdir build
  - cd build
  - cmake .. -DPython_ROOT_DIR=$HOME/miniconda -DBOOST_ROOT=/usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0 -DBUILD_TESTS=ON -DBUILD_MULTIPLE_TEST=ON -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS=ON -DBUILD_EXAMPLE_README=ON
  - cmake --build . --config Release --target NumCppPy
  - cmake --build . --config Release --target Multiple
  - cmake --build . --config Release --target GaussNewtonNlls
  - cmake --build . --config Release --target ReadMe
  - sudo make install
  - cd ../test/pytest
  - $HOME/miniconda/bin/python -m pytest
