os: linux
dist: focal
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt update
  - sudo apt remove --purge cmake python
  - sudo apt install -y libboost-all-dev libtbb-dev
  - dpkg -L libboost-all-dev
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env update --file ${TRAVIS_BUILD_DIR}/test/pytest/environment.yml --name base
install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.23/cmake-3.23.2-linux-x86_64.tar.gz
  - tar -xvf cmake-3.23.2-linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.23.2-linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cmake --version
  - cd ${TRAVIS_BUILD_DIR}
script:
  - mkdir build
  - cd build
  - cmake .. -DPython_ROOT_DIR=$HOME/miniconda -DBUILD_TESTS=ON -DBUILD_MULTIPLE_TEST=ON -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS=ON -DBUILD_EXAMPLE_README=ON
  - cmake --build . --config Release --target NumCppPy
  - cmake --build . --config Release --target Multiple
  - cmake --build . --config Release --target GaussNewtonNlls
  - cmake --build . --config Release --target ReadMe
  - sudo make install
  - cd ../test/pytest
  - $HOME/miniconda/bin/python -m pytest
