dist: focal
sudo: required
language: cpp

notifications:
  email: false

before_install:
  - sudo apt update
  - sudo apt remove --purge cmake
  - hash -r
  - sudo snap install cmake --classic
  - sudo apt install libboost-all-dev

script:
  - mkdir build
  - cd build
  - cmake .. -DNUMCPP_EXAMPLES=True -DEXAMPLE_GAUSS_NEWTON_NLLS=True -DEXAMPLE_README=True -DBOOST_ROOT=C:\Libraries\boost_1_73_0
  - cmake --build . --config Release --target GaussNewtonNlls
  - cmake --build . --config Release --target ReadMe
  - cmake --build . --config Release --target install
