name: Linux Environment Setup
description: "Sets up the linux environment"

env:
  BOOST_ROOT: /home/runner/boost

runs:
  using: "composite"
  steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Add conda to system path
      shell: bash
      run: |
        $CONDA/bin/conda init --all

    - name: Install dependencies
      shell: bash
      run: |
        $CONDA/bin/conda env update --file ${{github.workspace}}/test/pytest/environment.yml --name base

    - name: Install Dependency libs
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y libtbb-dev

    - name: Install boost
      uses: MarkusJx/install-boost@v2.3.0
      id: install-boost
      with:
        # REQUIRED: Specify the required boost version
        # A list of supported versions can be found here:
        # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
        boost_version: 1.73.0
        platform_version: 20.04
        boost_install_dir: ${{env.BOOST_ROOT}}
        toolset: gcc
        arch: x86
