name: Linux Environment Setup
description: "Sets up the linux environment"

inputs:
  use_clang:
    description: “Configure clang and the built tools”
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: false
        activate-environment: test
        environment-file: test/pytest/environment.yml
        python-version: 3.9

    - name: Activate Env
      shell: bash -l {0}
      run: |
        conda activate test 

    - name: Install Dependency libs
      shell: bash -l {0}
      run: |
        sudo apt update
        sudo apt install -y clang
        sudo apt install -y libboost-all-dev
        if [${{inputs.use_clang}}] then CXX=clang++ CC=clang fi
