name: CMake

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS -DBUILD_MULTIPLE_TESTS -DBUILD_EXAMPLE_README -DBUILD_EXAMPLE_GAUSS_NEWTON_NLLS

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/test/pytestl
        run: pytest
