name: Static analysis

on:
  push:
  pull_request:
    branches: ["master", "develop"]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependency libs
      shell: bash -l {0}
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        exclude_dir: test
        force_console_print: true
