name: Static analysis

on:
  push:
  pull_request:
    branches: ["master", "develop"]

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@master
      with:
        exclude_dir: test
        use_cmake: true
        apt_pckgs: libboost-all-dev
        force_console_print: true
